// ACTION TYPES involved in app:
const ACTION_TYPES = {
  // Reading:
  READ_SPREADSHEET: 'READ_SPREADSHEET',
  // Testing text:
  TEST_INIT: 'TEST_INIT',
  TEST_CLEAR: 'TEST_CLEAR',
  TEST_SPREADSHEET: 'TEST_SPREADSHEET',
  TEST_SPREADSHEET_ITEM: 'TEST_SPREADSHEET_ITEM',
};

export default ACTION_TYPES;
