// ACTION TYPES involved in app:
const ACTION_TYPES = {
  // Reading:
  READ_SPREADSHEET: 'READ_SPREADSHEET',
  // Testing text:
  TEST_INIT: 'TEST_INIT',
  TEST_CLEAR: 'TEST_CLEAR',
  TEST_SPREADSHEET: 'TEST_SPREADSHEET',
  TEST_SPREADSHEET_ITEM: 'TEST_SPREADSHEET_ITEM',
  TEST_SCHEMA_INIT: 'TEST_SCHEMA_INIT',
  TEST_SPREADSHEET_SCHEMA: 'TEST_SPREADSHEET_SCHEMA',
  TEST_SHEET_LEVEL_ITEM_INIT: 'TEST_SHEET_LEVEL_ITEM_INIT',
  TEST_SHEET_LEVEL_ITEM: 'TEST_SHEET_LEVEL_ITEM',
  TEST_ACROSS_SHEET_ITEM_INIT: 'TEST_ACROSS_SHEET_ITEM_INIT',
  TEST_ACROSS_SHEET_ITEM: 'TEST_ACROSS_SHEET_ITEM',
};

export default ACTION_TYPES;
